---

- name: Setting user's home permissions
  ansible.builtin.file:
    dest: "{{ _users_home }}"
    owner: "{{ _users_uid }}"
    group: "{{ _users_group }}"
    mode: "{{ _users_home_mode }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Adding user's .ssh directory
  ansible.builtin.file:
    path: "{{ _users_home }}/.ssh"
    owner: "{{ _users_uid }}"
    group: "{{ _users_group }}"
    state: directory
    mode: "{{ _users_home_ssh_mode }}"

- name: Adding user's private SSH key
  ansible.builtin.copy:
    content: "{{ user.ssh_key }}"
    dest: "{{ _users_home }}/.ssh/id_{{ user.ssh_key_type | default('rsa') }}"
    owner: "{{ _users_uid }}"
    group: "{{ _users_group }}"
    mode: "0600"
  when: user.ssh_key is defined
  no_log: true

- name: Adding user's private keys
  ansible.builtin.copy:
    content: "{{ item.value }}"
    dest: "{{ _users_home }}/.ssh/{{ item.key }}"
    owner: "{{ _users_username }}"
    group: "{{ _users_group }}"
    mode: "0600"
  when: user.ssh_key is not defined and user.ssh_keys is defined
  with_dict: "{{ user.ssh_keys }}"
