---
- name: Converge
  hosts: all
  vars:
    users:
      - username: testuser
        group: testgroup
        groups:
          - sudo
        home_mode: "0750"
        authorized_keys:
          - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAITestKeyForMolecule testuser@molecule"
        ssh_key_generate: true
        ssh_key_type: ed25519
      - username: giduser
    users_group:
      name: testgroup
      gid: 1050
    users_groups:
      - name: testgroup2
        gid: 1051
  roles:
    - role: brianhartsock.users

- name: Converge (no users_group set)
  hosts: all
  vars:
    users:
      - username: defaultuser
  roles:
    - role: brianhartsock.users

- name: Converge (user_update, step 1)
  hosts: all
  vars:
    users:
      - username: testuser_update1
        group: testgroup
        user_update: on_create
        home_create: false
        home: "/home/update1"
      - username: testuser_update1
        group: testgroup
        user_update: "always"
        home_create: false
        home: "/home/update1a"
      - username: testuser_update2
        group: testgroup
        user_update: on_create
        home_create: false
        home: "/home/update2"
      - username: testuser_update2
        group: testgroup
        user_update: "on_create"
        home_create: false
        home: "/home/update2a"
  roles:
    - role: brianhartsock.users
