---
- name: Prepare
  hosts: all
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install openssh-client
      ansible.builtin.apt:
        name: openssh-client
